#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Sep 01, 2015 12:30:55 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import UI_support
from tkinter import filedialog


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('New_Toplevel_1')
    geom = "600x450+339+245"
    root.geometry(geom)
    w = New_Toplevel_1 (root)
    UI_support.init(root, w)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('New_Toplevel_1')
    geom = "600x600+300+200"
    w.geometry(geom)
    w_win = New_Toplevel_1 (w)
    UI_support.init(w, w_win, param)
    return w_win

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.frame_folder = LabelFrame(master)
        self.frame_folder.place(x=15, y=15, height=60, width=570)
        self.frame_folder.configure(relief=GROOVE)
        self.frame_folder.configure(foreground="black")
        self.frame_folder.configure(text='''Select Folder''')
        self.frame_folder.configure(background=_bgcolor)
        self.frame_folder.configure(highlightbackground="#d9d9d9")
        self.frame_folder.configure(highlightcolor="black")
        self.frame_folder.configure(width=560)

        self.entry_path = Entry(self.frame_folder)
        self.entry_path.place(x=10, y=10, height=20, width=375)
        self.entry_path.configure(background="white")
        self.entry_path.configure(disabledforeground="#a3a3a3")
        self.entry_path.configure(font="TkFixedFont")
        self.entry_path.configure(foreground="#000000")
        self.entry_path.configure(highlightbackground="#d9d9d9")
        self.entry_path.configure(highlightcolor="black")
        self.entry_path.configure(insertbackground="black")
        self.entry_path.configure(selectbackground="#c4c4c4")
        self.entry_path.configure(selectforeground="black")

        self.button_browse = Button(self.frame_folder,command=self.loadfolder)
        self.button_browse.place(x=400, y=10, height=20, width=70)
        self.button_browse.configure(activebackground="#d9d9d9")
        self.button_browse.configure(activeforeground="#000000")
        self.button_browse.configure(background=_bgcolor)
        self.button_browse.configure(disabledforeground="#a3a3a3")
        self.button_browse.configure(foreground="#000000")
        self.button_browse.configure(highlightbackground="#d9d9d9")
        self.button_browse.configure(highlightcolor="black")
        self.button_browse.configure(pady="0")
        self.button_browse.configure(text='''Browse''')

        self.button_load_folder = Button(self.frame_folder)
        self.button_load_folder.place(x=485, y=10, height=20, width=70)
        self.button_load_folder.configure(activebackground="#d9d9d9")
        self.button_load_folder.configure(activeforeground="#000000")
        self.button_load_folder.configure(background=_bgcolor)
        self.button_load_folder.configure(disabledforeground="#a3a3a3")
        self.button_load_folder.configure(foreground="#000000")
        self.button_load_folder.configure(highlightbackground="#d9d9d9")
        self.button_load_folder.configure(highlightcolor="black")
        self.button_load_folder.configure(pady="0")
        self.button_load_folder.configure(text='''Load''')

        self.frame_info = LabelFrame(master)
        self.frame_info.place(x=15, y=90, height=60, width=570)
        self.frame_info.configure(relief=GROOVE)
        self.frame_info.configure(foreground="black")
        self.frame_info.configure(text='''Information''')
        self.frame_info.configure(background=_bgcolor)
        self.frame_info.configure(highlightbackground="#d9d9d9")
        self.frame_info.configure(highlightcolor="black")
        self.frame_info.configure(width=560)

        self.label_scan = ttk.Label(self.frame_info)
        self.label_scan.place(x=10, y=10, height=20, width=80)
        self.label_scan.configure(background=_bgcolor)
        self.label_scan.configure(foreground="#000000")
        self.label_scan.configure(relief=FLAT)
        self.label_scan.configure(text='''Scan Number''')

        self.entry_scan = Entry(self.frame_info)
        self.entry_scan.place(x=90, y=10, height=20, width=80)
        self.entry_scan.configure(background="white")
        self.entry_scan.configure(disabledforeground="#a3a3a3")
        self.entry_scan.configure(font="TkFixedFont")
        self.entry_scan.configure(foreground="#000000")
        self.entry_scan.configure(highlightbackground="#d9d9d9")
        self.entry_scan.configure(highlightcolor="black")
        self.entry_scan.configure(insertbackground="black")
        self.entry_scan.configure(selectbackground="#c4c4c4")
        self.entry_scan.configure(selectforeground="black")

        self.frame_img = ttk.Labelframe(master)
        self.frame_img.place(x=15, y=165, height=60, width=570)
        self.frame_img.configure(text='''IMG File''')
        self.frame_img.configure(width=560)

        self.entry_img_path = Entry(self.frame_img)
        self.entry_img_path.place(x=10, y=10, height=20, width=375)
        self.entry_img_path.configure(background="white")
        self.entry_img_path.configure(disabledforeground="#a3a3a3")
        self.entry_img_path.configure(font="TkFixedFont")
        self.entry_img_path.configure(foreground="#000000")
        self.entry_img_path.configure(highlightbackground="#d9d9d9")
        self.entry_img_path.configure(highlightcolor="black")
        self.entry_img_path.configure(insertbackground="black")
        self.entry_img_path.configure(selectbackground="#c4c4c4")
        self.entry_img_path.configure(selectforeground="black")

        self.button_load_img = Button(self.frame_img)
        self.button_load_img.place(x=400, y=10, height=20, width=70)
        self.button_load_img.configure(activebackground="#d9d9d9")
        self.button_load_img.configure(activeforeground="#000000")
        self.button_load_img.configure(background=_bgcolor)
        self.button_load_img.configure(disabledforeground="#a3a3a3")
        self.button_load_img.configure(foreground="#000000")
        self.button_load_img.configure(highlightbackground="#d9d9d9")
        self.button_load_img.configure(highlightcolor="black")
        self.button_load_img.configure(pady="0")
        self.button_load_img.configure(text='''Load''')

        self.button_save_img = Button(self.frame_img)
        self.button_save_img.place(x=485, y=10, height=20, width=70)
        self.button_save_img.configure(activebackground="#d9d9d9")
        self.button_save_img.configure(activeforeground="#000000")
        self.button_save_img.configure(background=_bgcolor)
        self.button_save_img.configure(disabledforeground="#a3a3a3")
        self.button_save_img.configure(foreground="#000000")
        self.button_save_img.configure(highlightbackground="#d9d9d9")
        self.button_save_img.configure(highlightcolor="black")
        self.button_save_img.configure(pady="0")
        self.button_save_img.configure(text='''Save''')

    def loadfolder(self):
        self.path = filedialog.askdirectory()
        self.entry_path.insert(0,self.path)


if __name__ == '__main__':
    vp_start_gui()



